"""added expires_at column

Revision ID: 7311e1f7fc52
Revises: 8d6db6ffc255
Create Date: 2026-04-02 11:09:52.582192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7311e1f7fc52'
down_revision: Union[str, Sequence[str], None] = '8d6db6ffc255'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'expires_at')
    # ### end Alembic commands ###
